baseURL = "https://lpeasy.github.io/outsideinprint/"
title = "Outside In Print"
languageCode = "en-us"

enableRobotsTXT = true
disableKinds = ["taxonomy", "term"]

[permalinks]
essays = "/essays/:slug/"
literature = "/literature/:slug/"
reports = "/reports/:slug/"
working-papers = "/working-papers/:slug/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = false
